spring:
  application:
    name: spring-batch
  data:
    rest:
      base-path: /api
    mongodb:
      database: batchdb
      uri: mongodb+srv://${dbuser}:${dbcreds}@${mongo_server}/
  batch:
    jdbc:
      platform: postgresql
      initialize-schema: never
    job:
      enabled: true
      name: csvJob
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${pg_server}:5432/batchdb?currentSchema=batchdb
    username: ${pguser}
    password: ${pgcreds}
    hikari:
      schema: batchdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info
    .: info
    sun:
      rmi: error
    javax:
      management: error
    org:
      springdoc:
        jdbc:
          core: trace

springdoc:
  show-actuator: true
  swagger-ui:
    show-extensions: true
    show-common-extensions: true